import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import {
  extractTextFromBytes,
  validateDocFile,
  DocumentExtractionError,
  PDF_MIME,
  DOCX_MIME,
  MAX_DOC_SIZE,
} from "~/lib/documents/extract";

const fixture = (name: string) =>
  new Uint8Array(readFileSync(fileURLToPath(new URL(`../fixtures/${name}`, import.meta.url))));

/**
 * The extractor is the deep module behind the new `document` upload control:
 * bytes + MIME → plain text for the textarea. Fixtures are real (multi-page)
 * PDF and DOCX files generated by tests/fixtures/generate.mjs.
 */
describe("document extraction", () => {
  it("extracts text from every page of a PDF", async () => {
    const result = await extractTextFromBytes(fixture("sample.pdf"), PDF_MIME);
    expect(result.empty).toBe(false);
    expect(result.pageCount).toBe(2);
    expect(result.text).toContain("STAGEFIXTUREPAGEONE");
    expect(result.text).toContain("STAGEFIXTUREPAGETWO");
  });

  it("extracts text from a DOCX", async () => {
    const result = await extractTextFromBytes(fixture("sample.docx"), DOCX_MIME);
    expect(result.empty).toBe(false);
    expect(result.text).toContain("STAGEFIXTUREDOCX");
    expect(result.text).toContain("Tweede alinea");
  });

  it("flags a scanned / image-only PDF as empty (paste-instead signal)", async () => {
    const result = await extractTextFromBytes(fixture("sample-empty.pdf"), PDF_MIME);
    expect(result.empty).toBe(true);
    expect(result.text).toBe("");
  });

  it("throws a typed error for an unsupported MIME type", async () => {
    await expect(extractTextFromBytes(fixture("sample.pdf"), "text/plain")).rejects.toBeInstanceOf(
      DocumentExtractionError,
    );
  });

  it("does not flag a normal report as large", async () => {
    const result = await extractTextFromBytes(fixture("sample.docx"), DOCX_MIME);
    expect(result.large).toBe(false);
  });
});

describe("upload validation (boundary)", () => {
  it("accepts a PDF and a DOCX within the size cap", () => {
    expect(validateDocFile(1024, PDF_MIME)).toBeUndefined();
    expect(validateDocFile(1024, DOCX_MIME)).toBeUndefined();
  });

  it("rejects a disallowed MIME type", () => {
    expect(validateDocFile(1024, "image/png")).toMatch(/Unsupported file type/i);
    expect(validateDocFile(1024, "")).toMatch(/Unsupported file type/i);
  });

  it("rejects a file over the size cap", () => {
    expect(validateDocFile(MAX_DOC_SIZE + 1, PDF_MIME)).toMatch(/too large/i);
  });
});
