import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import {
  extractTextFromBytes,
  filesToDocumentText,
  validateDocFile,
  DocumentExtractionError,
  PDF_MIME,
  DOCX_MIME,
  MAX_DOC_SIZE,
} from "~/lib/documents/extract";

const fixture = (name: string) =>
  new Uint8Array(readFileSync(fileURLToPath(new URL(`../fixtures/${name}`, import.meta.url))));

const fixtureFile = (name: string, type: string) => new File([fixture(name)], name, { type });

/**
 * The extractor is the deep module behind the new `document` upload control:
 * bytes + MIME → plain text for the textarea. Fixtures are real (multi-page)
 * PDF and DOCX files generated by tests/fixtures/generate.mjs.
 */
describe("document extraction", () => {
  it("extracts text from every page of a PDF", async () => {
    const result = await extractTextFromBytes(fixture("sample.pdf"), PDF_MIME);
    expect(result.empty).toBe(false);
    expect(result.pageCount).toBe(2);
    expect(result.text).toContain("STAGEFIXTUREPAGEONE");
    expect(result.text).toContain("STAGEFIXTUREPAGETWO");
  });

  it("extracts text from a DOCX", async () => {
    const result = await extractTextFromBytes(fixture("sample.docx"), DOCX_MIME);
    expect(result.empty).toBe(false);
    expect(result.text).toContain("STAGEFIXTUREDOCX");
    expect(result.text).toContain("Tweede alinea");
  });

  it("flags a scanned / image-only PDF as empty (paste-instead signal)", async () => {
    const result = await extractTextFromBytes(fixture("sample-empty.pdf"), PDF_MIME);
    expect(result.empty).toBe(true);
    expect(result.text).toBe("");
  });

  it("throws a typed error for an unsupported MIME type", async () => {
    await expect(extractTextFromBytes(fixture("sample.pdf"), "text/plain")).rejects.toBeInstanceOf(
      DocumentExtractionError,
    );
  });

  it("does not flag a normal report as large", async () => {
    const result = await extractTextFromBytes(fixture("sample.docx"), DOCX_MIME);
    expect(result.large).toBe(false);
  });
});

describe("merging multiple uploaded files", () => {
  it("concatenates several files with per-file headings (whole-portfolio case)", async () => {
    const merged = await filesToDocumentText([
      fixtureFile("sample.pdf", PDF_MIME),
      fixtureFile("sample.docx", DOCX_MIME),
    ]);
    expect(merged.emptyFiles).toEqual([]);
    // Both documents' text is present...
    expect(merged.text).toContain("STAGEFIXTUREPAGEONE");
    expect(merged.text).toContain("STAGEFIXTUREDOCX");
    // ...each under a heading naming its file, so the parts stay distinguishable.
    expect(merged.text).toContain("## sample.pdf");
    expect(merged.text).toContain("## sample.docx");
  });

  it("does not add a heading for a single file", async () => {
    const merged = await filesToDocumentText([fixtureFile("sample.pdf", PDF_MIME)]);
    expect(merged.text).not.toContain("##");
    expect(merged.text).toContain("STAGEFIXTUREPAGEONE");
  });

  it("reports files with no readable text instead of failing the batch", async () => {
    const merged = await filesToDocumentText([
      fixtureFile("sample.docx", DOCX_MIME),
      fixtureFile("sample-empty.pdf", PDF_MIME),
    ]);
    expect(merged.emptyFiles).toEqual(["sample-empty.pdf"]);
    expect(merged.text).toContain("STAGEFIXTUREDOCX");
  });

  it("rejects an invalid file in the batch, naming it", async () => {
    const badFile = new File([new Uint8Array([1, 2, 3])], "note.txt", { type: "text/plain" });
    await expect(
      filesToDocumentText([fixtureFile("sample.pdf", PDF_MIME), badFile]),
    ).rejects.toThrow(/note\.txt/);
  });
});

describe("upload validation (boundary)", () => {
  it("accepts a PDF and a DOCX within the size cap", () => {
    expect(validateDocFile(1024, PDF_MIME)).toBeUndefined();
    expect(validateDocFile(1024, DOCX_MIME)).toBeUndefined();
  });

  it("rejects a disallowed MIME type", () => {
    expect(validateDocFile(1024, "image/png")).toMatch(/Unsupported file type/i);
    expect(validateDocFile(1024, "")).toMatch(/Unsupported file type/i);
  });

  it("rejects a file over the size cap", () => {
    expect(validateDocFile(MAX_DOC_SIZE + 1, PDF_MIME)).toMatch(/too large/i);
  });
});
